services:
  # База данных
  db:
    image: postgres:15-alpine
    container_name: deribit_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deribit_tracker
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Брокер
  redis:
    image: redis:alpine
    container_name: deribit_redis
    ports:
      - "6379:6379"
    restart: always

  # API
  app:
    build: . 
    container_name: deribit_api
    env_file:
      - .env 
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    # Сначала сработает entrypoint, а потом запустится uvicorn
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: always

  # Воркер и планировщик
  worker:
    build: . 
    container_name: deribit_celery
    env_file:
      - .env
    depends_on:
      - db
      - redis
    # Тут сработает entrypoint (проверит базу) и запустит Celery
    command: celery -A app.worker.celery_app worker -B --loglevel=info
    restart: always

volumes:
  postgres_data: