"""initial

Revision ID: 40f2c862f630
Revises: 
Create Date: 2026-03-13 12:28:32.810798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f2c862f630'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_prices_ticker'), 'crypto_prices', ['ticker'], unique=False)
    op.create_index(op.f('ix_crypto_prices_timestamp'), 'crypto_prices', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_prices_timestamp'), table_name='crypto_prices')
    op.drop_index(op.f('ix_crypto_prices_ticker'), table_name='crypto_prices')
    op.drop_table('crypto_prices')
    # ### end Alembic commands ###
